# GRADLE
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# MC & NEO
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.209
loader_version_range=[1,)

mod_id=emi_create_schematics
mod_name=Create: EMI Schematics
mod_license=MIT
mod_version=1.1.0
mod_group_id=net.liukrast
mod_authors=LiukRast, swzo
mod_description=Bored to switch between crafting and §6Create§r's clipboard?\nSave all items from a clipboard to §bEMI Favourites§r!\n§7[§e!§7]§c Also shows items amount!§r

# Publish
curse_id=940673
modrinth_id=5bgqgixq
dependencies=create(required){modrinth:LNytGWDc}{curseforge:328085}#(ignore:github)
java_version=21
mod_loader=neoforge

create_version_range=[6.0.9,)
create_version = 6.0.9-216
ponder_version = 1.0.81
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67
emi_version = 1.1.22+1.21.1
