org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.169
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
mod_id=emi_create_schematics
mod_name=Emi Create Schematics
mod_license=MIT
mod_version=1.0.2
mod_group_id=net.liukrast
mod_authors=LiukRast
mod_description=Bored to switch between crafting and @Create's clipboard? Save all items from a clipboard to EMI: Favourites!\n-> Also shows items amount!

create_version = 6.0.4-53
ponder_version = 1.0.46
flywheel_version = 1.0.2
registrate_version = MC1.21-1.3.0+62
emi_version = 1.1.22+1.21.1
