
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="emi_create_schematics"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile = "icon.png"
credits="Hemerald's idea, Developed by LiukRast"

description='''${mod_description}'''

[[dependencies.emi_create_schematics]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.emi_create_schematics]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.emi_create_schematics]]
modId="create"
mandatory=true
versionRange="0.5.1c"
ordering="NONE"
side="BOTH"
[[dependencies.emi_create_schematics]]
modId="emi"
mandatory=true
versionRange="1.0.24+1.19.2"
ordering="NONE"
side="BOTH"
