modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/LIUKRAST/EmiCreateSchematics/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL="https://liukrast.net/"
logoFile="${mod_id}.png"
credits="to §9Hemerald§r, which requested this mod in the first place"
authors = "${mod_authors}"
description = '''${mod_description}'''
[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "create"
type = "required"
versionRange = "${create_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "emi"
type = "required"
versionRange = "[1.1.22+1.21.1,)"
ordering = "NONE"
side = "CLIENT"